# Copyright (c) 2026, earthians Health Informatics Pvt. Ltd. and contributors
# For license information, please see license.txt

import frappe


class FHIRValueResolutionError(Exception):
	pass


class FHIRValueResolver:
	"""
	Resolves values using a compiled mapping into a flat dict:
	  - fhir_path -> value

	Supports value_spec kinds:
	  - fixed
	  - field
	  - child_table_rows   (generated by compiler collapse)
	"""

	def __init__(self, compiled_map, primary_name):
		self.compiled_map = compiled_map or {}
		self.primary_name = primary_name

		self.sources = self.compiled_map.get("sources") or {}
		self.elements = self.compiled_map.get("elements") or {}

		self.source_data = {}
		self.resolved_values = {}

	def resolve(self):
		self.validate_required_fields()
		self.load_sources()
		self.resolve_elements()
		return self.resolved_values

	def validate_required_fields(self):
		if not self.primary_name:
			raise FHIRValueResolutionError("primary_name is required.")
		if not self.compiled_map:
			raise FHIRValueResolutionError("compiled_map is required.")

	# =========================================================
	# Sources
	# =========================================================

	def load_sources(self):
		"""Load all source documents in dependency order."""
		# primary sources (no dependencies)
		for key, config in self.sources.items():
			if self._get_kind(config) == "primary":
				self.source_data[key] = self.load_primary(config)
				break

		# linked sources (depend on primary)
		for key, config in self.sources.items():
			kind = self._get_kind(config)
			if kind == "direct_link":
				self.source_data[key] = self.load_direct_link(config)
			elif kind == "reverse_link":
				self.source_data[key] = self.load_reverse_link(config)

	def load_primary(self, config):
		doctype = self._get_str(config, "doctype")
		if not doctype:
			return None

		try:
			return frappe.get_doc(doctype, self.primary_name).as_dict()
		except frappe.DoesNotExistError:
			return None

	def load_direct_link(self, config):
		doctype = self._get_str(config, "doctype")
		link_fieldname = self._get_str(config, "link_fieldname")
		from_source = self._get_str(config, "from_source") or "primary"

		if not doctype or not link_fieldname:
			return None

		parent_doc = self.source_data.get(from_source)
		if not parent_doc:
			return None

		linked_name = parent_doc.get(link_fieldname)
		if not linked_name:
			return None

		lookup_field = self._get_str(config, "lookup_fieldname")
		if lookup_field:
			linked_name = frappe.db.get_value(doctype, {lookup_field: linked_name}, "name")
			if not linked_name:
				return None

		try:
			return frappe.get_doc(doctype, linked_name).as_dict()
		except frappe.DoesNotExistError:
			return None

	def load_reverse_link(self, config):
		doctype = self._get_str(config, "doctype")
		link_fieldname = self._get_str(config, "link_fieldname")
		from_source = self._get_str(config, "from_source") or "primary"

		if not doctype or not link_fieldname:
			return []

		parent_doc = self.source_data.get(from_source)
		if not parent_doc:
			return []

		parent_name = parent_doc.get("name")
		if not parent_name:
			return []

		filters = {link_fieldname: parent_name}
		extra_filters = config.get("filters")
		if extra_filters:
			filters.update(extra_filters)

		order_by = self._get_str(config, "order_by") or "creation desc"
		limit = config.get("limit")

		names = frappe.get_all(
			doctype,
			filters=filters,
			order_by=order_by,
			pluck="name",
			limit=limit,
		)

		docs = []
		for name in names:
			try:
				docs.append(frappe.get_doc(doctype, name).as_dict())
			except frappe.DoesNotExistError:
				continue

		return docs

	# =========================================================
	# Elements
	# =========================================================

	def resolve_elements(self):
		"""Resolve all element values into flat dict."""
		for element_path in list(self.elements.keys()):
			element = self.elements.get(element_path)
			if not element:
				continue

			value = self.resolve_element(element)
			if value is not None:
				self.resolved_values[element_path] = value

	def resolve_element(self, element):
		value_spec = element.get("value_spec") or {}
		kind = self._get_str(value_spec, "kind")

		if kind == "fixed":
			return self.resolve_fixed(value_spec, element)

		if kind == "field":
			return self.resolve_field(value_spec, element)

		if kind == "child_table_rows":
			return self.resolve_child_table_rows(value_spec)

		if kind == "object_group":
			return self.resolve_object_group(value_spec)

		return None

	def resolve_fixed(self, value_spec, element):
		value = value_spec.get("value")
		return self._coerce(value, element.get("datatype"))

	def resolve_field(self, value_spec, element):
		source_key = self._get_str(value_spec, "source_key")
		fieldname = self._get_str(value_spec, "fieldname")

		if not source_key or not fieldname:
			return None

		source = self.source_data.get(source_key)
		if source is None:
			return None

		datatype = element.get("datatype")

		if isinstance(source, list):
			return self.resolve_from_list(source, fieldname, datatype)

		return self.resolve_from_doc(source, fieldname, datatype)

	def resolve_child_table_rows(self, value_spec):
		"""
		Resolve a child table to list[dict] by mapping each row to a complex object.

		Supports:
		  - source_key resolving to single dict (primary/direct_link)
		  - source_key resolving to list[dict] (reverse_link)

		value_spec:
		  - source_key
		  - table_fieldname
		  - row_mapping: { fhir_key: row_fieldname }
		  - row_constraints: { fhir_key: { min, datatype, regex, ... } }   (optional)
		"""
		source_key = self._get_str(value_spec, "source_key")
		table_fieldname = self._get_str(value_spec, "table_fieldname")
		row_mapping = value_spec.get("row_mapping") or {}
		row_constraints = value_spec.get("row_constraints") or {}

		if not source_key or not table_fieldname or not isinstance(row_mapping, dict):
			return None

		source = self.source_data.get(source_key)
		if source is None:
			return None

		# Collect rows from one doc OR many docs
		all_rows = []

		if isinstance(source, list):
			for doc in source:
				if not isinstance(doc, dict):
					continue
				rows = self._read_field(doc, table_fieldname)
				if isinstance(rows, list):
					for row in rows:
						if isinstance(row, dict):
							all_rows.append(row)
		else:
			rows = self._read_field(source, table_fieldname)
			if isinstance(rows, list):
				for row in rows:
					if isinstance(row, dict):
						all_rows.append(row)

		if not all_rows:
			return None

		result = []
		for row_index, row in enumerate(all_rows):
			out = {}

			for fhir_key, row_fieldname in row_mapping.items():
				fhir_key = str(fhir_key or "").strip()
				row_fieldname = str(row_fieldname or "").strip()
				if not fhir_key or not row_fieldname:
					continue

				raw_value = self._read_field(row, row_fieldname)

				constraints = row_constraints.get(fhir_key) or {}
				min_required = int(constraints.get("min") or 0)
				field_datatype = (constraints.get("datatype") or "").strip()

				if raw_value is None:
					if min_required >= 1:
						raise FHIRValueResolutionError(
							f"child_table_rows missing required field '{fhir_key}' "
							f"in table '{table_fieldname}' row #{row_index + 1} (source_key='{source_key}')."
						)
					continue

				coerced = self._coerce(raw_value, field_datatype)
				if coerced is None:
					if min_required >= 1:
						raise FHIRValueResolutionError(
							f"child_table_rows field '{fhir_key}' coerced to None "
							f"in table '{table_fieldname}' row #{row_index + 1} (source_key='{source_key}')."
						)
					continue

				out[fhir_key] = coerced

			# Skip empty rows
			if out:
				result.append(out)

		return result if result else None

	def resolve_object_group(self, value_spec):
		"""
		Build one complex object from embedded leaf specs, and optionally wrap in array.

		value_spec:
		  - children: { child_key: { value_spec, datatype, min, ... } }
		  - wrap_in_array: bool
		"""
		children = value_spec.get("children") or {}
		wrap_in_array = bool(value_spec.get("wrap_in_array"))

		if not isinstance(children, dict) or not children:
			return None

		out = {}

		for child_key, embedded_leaf in children.items():
			child_key = str(child_key or "").strip()
			if not child_key or not isinstance(embedded_leaf, dict):
				continue

			value = self.resolve_embedded_leaf(embedded_leaf, child_key)
			if value is not None:
				out[child_key] = value

		if not out:
			return None

		return [out] if wrap_in_array else out

	def resolve_embedded_leaf(self, embedded_leaf, child_key):
		"""
		Resolve an embedded leaf spec (no dependency on elements table).

		embedded_leaf contains:
		  - value_spec (fixed/field)
		  - datatype
		  - min (required)
		"""
		leaf_value_spec = embedded_leaf.get("value_spec") or {}
		kind = (leaf_value_spec.get("kind") or "").strip()
		datatype = (embedded_leaf.get("datatype") or "").strip()
		min_required = int(embedded_leaf.get("min") or 0)

		if kind == "fixed":
			value = leaf_value_spec.get("value")
			value = self._coerce(value, datatype)
			if value is None and min_required >= 1:
				raise FHIRValueResolutionError(f"object_group missing required '{child_key}' (fixed value).")
			return value

		if kind == "field":
			source_key = self._get_str(leaf_value_spec, "source_key")
			fieldname = self._get_str(leaf_value_spec, "fieldname")

			if not source_key or not fieldname:
				if min_required >= 1:
					raise FHIRValueResolutionError(f"object_group missing required '{child_key}' (field pointer incomplete).")
				return None

			source = self.source_data.get(source_key)
			if source is None:
				if min_required >= 1:
					raise FHIRValueResolutionError(f"object_group missing required '{child_key}' (source '{source_key}' not loaded).")
				return None

			# Reverse link list vs single doc
			if isinstance(source, list):
				value = self.resolve_from_list(source, fieldname, datatype)
			else:
				value = self.resolve_from_doc(source, fieldname, datatype)

			if value is None and min_required >= 1:
				raise FHIRValueResolutionError(
					f"object_group missing required '{child_key}' (source_key='{source_key}', fieldname='{fieldname}')."
				)
			return value

		# Unsupported embedded leaf kind
		if min_required >= 1:
			raise FHIRValueResolutionError(f"object_group missing required '{child_key}' (unsupported kind '{kind}').")
		return None

	def resolve_from_doc(self, doc, fieldname, datatype):
		value = self._read_field(doc, fieldname)
		if value is None:
			return None

		# If field itself is a list (child table), return coerced list
		if isinstance(value, list):
			result = []
			for item in value:
				coerced = self._coerce(item, datatype)
				if coerced is not None:
					result.append(coerced)
			return result if result else None

		return self._coerce(value, datatype)

	def resolve_from_list(self, docs, fieldname, datatype):
		result = []

		for doc in docs:
			value = self._read_field(doc, fieldname)
			if value is None:
				continue

			if isinstance(value, list):
				for item in value:
					coerced = self._coerce(item, datatype)
					if coerced is not None:
						result.append(coerced)
			else:
				coerced = self._coerce(value, datatype)
				if coerced is not None:
					result.append(coerced)

		return result if result else None

	# =========================================================
	# Coercion + field reading
	# =========================================================

	def _coerce(self, value, datatype):
		if value is None:
			return None

		# Preserve complex types as-is
		if isinstance(value, (list, dict)):
			return value

		if not datatype:
			return value

		primary_type = self._primary_datatype(datatype)

		try:
			if primary_type == "boolean":
				return self._to_bool(value)

			if primary_type == "integer":
				return int(value)

			if primary_type == "decimal":
				return float(value)

			if primary_type == "code":
				return str(value).strip().lower()

			if primary_type in ("string", "id", "uri", "url", "canonical", "markdown"):
				return str(value)

			if primary_type in ("date", "dateTime", "time", "instant"):
				return str(value)

			# Complex type convenience wrappers (only for scalar input)
			if primary_type == "Reference":
				return {"display": str(value)}

			if primary_type == "CodeableConcept":
				return {"text": str(value)}

			return value

		except (ValueError, TypeError):
			return value

	def _read_field(self, data, fieldname):
		"""
		Read a field using dot notation.
		Handles nested dicts and child tables (list of dicts).
		"""
		if not data or not fieldname:
			return None

		parts = fieldname.split(".")
		current = data

		for i, part in enumerate(parts):
			if current is None:
				return None

			if isinstance(current, dict):
				current = current.get(part)

			elif isinstance(current, list):
				remaining = ".".join(parts[i:])
				values = []
				for row in current:
					if isinstance(row, dict):
						val = self._read_field(row, remaining)
						if val is not None:
							if isinstance(val, list):
								values.extend(val)
							else:
								values.append(val)
				return values if values else None

			else:
				return None

		return current

	def _to_bool(self, value):
		if isinstance(value, bool):
			return value
		if isinstance(value, str):
			return value.strip().lower() in ("true", "1", "yes")
		return bool(value)

	def _primary_datatype(self, datatype):
		if not datatype:
			return ""
		parts = str(datatype).split(",")
		return parts[0].strip() if parts else ""

	def _get_str(self, obj, key):
		val = obj.get(key) if obj else None
		return val.strip() if isinstance(val, str) else ""

	def _get_kind(self, config):
		return self._get_str(config, "kind")
