patient_map = {
	"doctype": "FHIR Resource Map",
	"name": "MAP-Patient-Strict",
	"resource_type": "Patient",
	"fhir_version": "R4.0.1",
	"frappe_doctype": "Patient",
	"narrative_template": "Patient Narrative",
	"map": [
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.id",
			"fhir_datatype": "string",
			"frappe_field": "name",
		},
		{"doctype": "FHIR Resource Element Map", "fhir_path": "Patient.meta", "fhir_datatype": "Meta"},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.identifier",
			"fhir_datatype": "Identifier",
			"max": "*",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.identifier.system",
			"fhir_datatype": "uri",
			"default_value": "https://marley.health/patient-id",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.identifier.value",
			"fhir_datatype": "string",
			"frappe_field": "patient_id",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.name",
			"fhir_datatype": "HumanName",
			"max": "*",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.name.text",
			"fhir_datatype": "string",
			"frappe_field": "patient_name",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.name.family",
			"fhir_datatype": "string",
			"frappe_field": "last_name",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.name.given",
			"fhir_datatype": "string",
			"frappe_field": "first_name",
			"max": "*",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.telecom",
			"fhir_datatype": "ContactPoint",
			"max": "*",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.telecom.system",
			"fhir_datatype": "code",
			"default_value": "phone",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.telecom.value",
			"fhir_datatype": "string",
			"frappe_field": "mobile",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.telecom.rank",
			"fhir_datatype": "positiveInt",
			"default_value": 1,
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.gender",
			"fhir_datatype": "code",
			"frappe_field": "sex",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.birthDate",
			"fhir_datatype": "date",
			"frappe_field": "dob",
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.deceasedBoolean",
			"fhir_datatype": "boolean",
			"default_value": 0,
		},
		{
			"doctype": "FHIR Resource Element Map",
			"fhir_path": "Patient.address",
			"fhir_datatype": "Address",
			"max": "*",
		},
	],
}
